name: Build and Deploy Firmware

on:
  push:
    branches: 
      - work/esp8266*
  #pull_request:
  #  branches: [ github ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      lang: pl

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: pio run -e "lang_$lang"

      - name: Copy firmware
        run: |
          mkdir -p public
          cp .pio/build/lang_$lang/firmware.bin public/firmware-esp8266-$lang.bin

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Show public URL
        run: echo "Public Pages URL is ${{ steps.deployment.outputs.page_url }}"

